(function(){function performanceScalingImages(){function getAbsoluteURL(url){var a=window.document.createElement('a');a.href=url;return a.href}
var minLimit=100;var imagesData=[]
var images=Array.prototype.slice.call(document.getElementsByTagName('img'));for(var i=0,len=images.length;i<len;i++){var img=images[i];if(img.clientWidth+minLimit<img.naturalWidth&&img.clientWidth>0){imagesData.push(getAbsoluteURL(img.currentSrc))}}
return imagesData}
function performanceCssPrint(){function getAbsoluteURL(url){var a=window.document.createElement('a');a.href=url;return a.href}
var offending=[];var links=document.getElementsByTagName('link');for(var i=0,len=links.length;i<len;i++){if(links[i].media==='print'){offending.push(getAbsoluteURL(links[i].href))}}
return offending}
function performanceFastRender(){var util={getAbsoluteURL:function(url){var a=window.document.createElement('a');a.href=url;return a.href},exists:function(element,array){return array.some(function(e){return e===element})},getResourceHintsHrefs:function(type){var links=Array.prototype.slice.call(window.document.head.getElementsByTagName('link'));return links.filter(function(link){return link.rel===type}).map(function(link){return link.href})},getSynchJSFiles:function(parentElement){var scripts=Array.prototype.slice.call(parentElement.getElementsByTagName('script'));return scripts.filter(function(s){return!s.async&&s.src&&!s.defer}).map(function(s){return util.getAbsoluteURL(s.src)})},getCSSFiles:function(parentElement){var links=Array.prototype.slice.call(parentElement.getElementsByTagName('link'));return links.filter(function(link){return link.rel==='stylesheet'&&!link.href.startsWith('data:')}).map(function(link){return util.getAbsoluteURL(link.href)})},isHTTP2:function(){var type=util.getConnectionType().toLowerCase();return type==='h2'||type.startsWith('spdy')},getConnectionType:function(){if(window.performance.getEntriesByType('navigation')&&window.performance.getEntriesByType('navigation')[0]&&window.performance.getEntriesByType('navigation')[0].nextHopProtocol){return window.performance.getEntriesByType('navigation')[0].nextHopProtocol}else if(window.performance&&window.performance.getEntriesByType&&window.performance.getEntriesByType('resource')){var resources=window.performance.getEntriesByType('resource');if(resources.length>1&&resources[0].nextHopProtocol){var host=document.domain;for(var i=0,len=resources.length;i<len;i++){if(host===util.getHostname(resources[i].name)){return resources[i].nextHopProtocol}}}}
return'unknown'},getTransferSize:function(url){var entries=window.performance.getEntriesByName(url,'resource');if(entries.length===1&&typeof entries[0].transferSize==='number'){return entries[0].transferSize}else{return 0}},getHostname:function(url){var a=window.document.createElement('a');a.href=url;return a.hostname}}
var message='';var score=0;var offending=[];var styles=util.getCSSFiles(document.head);var scripts=util.getSynchJSFiles(document.head);var docDomain=document.domain;var domains=[];var blockingCSS=0;var blockingJS=0;var preconnects=util.getResourceHintsHrefs('preconnect');var preconnectDomains=preconnects.map(function(preconnect){return util.getHostname(preconnect)});function testByType(assetUrl){var domain=util.getHostname(assetUrl);if(domain!==docDomain){offending.push(assetUrl);if(!util.exists(domain,domains)){score+=util.exists(domain,preconnectDomains)?5:10;domains.push(domain)}
score+=5}else{offending.push(assetUrl);score+=5}}
if(util.isHTTP2()){if(styles.length>0){message='Make sure that the server pushes your CSS resources for faster rendering. ';styles.forEach(function(url){if(util.getTransferSize(url)>14500){offending.push(url);score+=5;blockingCSS++;message+='The style '+url+' is larger than the magic number TCP window size 14.5 kB. Make the file smaller and the page will render faster. '}})}
if(scripts.length>0){score+=scripts.length*10;scripts.forEach(function(url){offending.push(url);blockingJS++});message+="Avoid loading synchronously JavaScript inside of head, you shouldn't need JavaScript to render your page! "}}else{styles.forEach(function(style){testByType(style)});blockingCSS=styles.length;scripts.forEach(function(script){testByType(script)});blockingJS=scripts.length}
if(offending.length>0){message+='The page has '+blockingCSS+' render blocking CSS request(s) and '+blockingJS+' blocking JavaScript request(s) inside of head.'}
return[score,message,offending]}
function performanceGoogleTagManager(){return window.google_tag_manager===null}
function performanceInlineCss(){var util={isHTTP2:function(){var type=util.getConnectionType().toLowerCase();return type==='h2'||type.startsWith('spdy')},getConnectionType:function(){if(window.performance.getEntriesByType('navigation')&&window.performance.getEntriesByType('navigation')[0]&&window.performance.getEntriesByType('navigation')[0].nextHopProtocol){return window.performance.getEntriesByType('navigation')[0].nextHopProtocol}else if(window.performance&&window.performance.getEntriesByType&&window.performance.getEntriesByType('resource')){var resources=window.performance.getEntriesByType('resource');if(resources.length>1&&resources[0].nextHopProtocol){var host=document.domain;for(var i=0,len=resources.length;i<len;i++){if(host===util.getHostname(resources[i].name)){return resources[i].nextHopProtocol}}}}
return'unknown'},getAbsoluteURL:function(url){var a=window.document.createElement('a');a.href=url;return a.href},getCSSFiles:function(parentElement){var links=Array.prototype.slice.call(parentElement.getElementsByTagName('link'));return links.filter(function(link){return link.rel==='stylesheet'&&!link.href.startsWith('data:')}).map(function(link){return util.getAbsoluteURL(link.href)})}}
var message='';var score=0;var offending=[];var cssFilesInHead=util.getCSSFiles(document.head);var styles=Array.prototype.slice.call(window.document.head.getElementsByTagName('style'));if(util.isHTTP2()&&cssFilesInHead.length>0&&styles.length>0){score+=5;message='The page has both inline CSS and CSS requests even though it uses a HTTP/2-ish connection. If you have many users on slow connections, it can be better to only inline the CSS. Run your own tests and check the waterfall graph to see what happens.'}else if(util.isHTTP2()&&styles.length>0&&cssFilesInHead.length===0){message+='The page has inline CSS and uses HTTP/2. Do you have a lot of users with slow connections on the site? It is good to inline CSS when using HTTP/2. If not, and your server supports server push, you can probably push the CSS files instead.'}else if(util.isHTTP2()&&cssFilesInHead.length>0){message+='It is always faster for the user if you inline CSS instead of making a CSS request.'}
if(!util.isHTTP2()){if(cssFilesInHead.length>0&&styles.length===0){score+=10*cssFilesInHead.length;message='The page loads '+cssFilesInHead.length+' CSS request(s) inside of head, try to inline the CSS for the first render and lazy load the rest.';offending.push.apply(offending,cssFilesInHead)}
if(styles.length>0&&cssFilesInHead.length>0){score+=10;message+='The page has both inline styles as well as it is requesting '+cssFilesInHead.length+" CSS file(s) inside of the head. Let's only inline CSS for really fast render.";offending.push.apply(offending,cssFilesInHead)}}
return[score,message,offending]}
function performanceJQuery(){var versions=[];if(typeof window.jQuery==='function'){versions.push(window.jQuery.fn.jquery);var old=window.jQuery;while(old.fn&&old.fn.jquery){old=window.jQuery.noConflict(!0);if(!window.jQuery||!window.jQuery.fn){break}
if(old.fn.jquery===window.jQuery.fn.jquery){break}
versions.push(window.jQuery.fn.jquery)}}
return versions}
function performanceSPOF(){var util={getAbsoluteURL:function(url){var a=window.document.createElement('a');a.href=url;return a.href},getCSSFiles:function(parentElement){var links=Array.prototype.slice.call(parentElement.getElementsByTagName('link'));return links.filter(function(link){return link.rel==='stylesheet'&&!link.href.startsWith('data:')}).map(function(link){return util.getAbsoluteURL(link.href)})},getSynchJSFiles:function(parentElement){var scripts=Array.prototype.slice.call(parentElement.getElementsByTagName('script'));return scripts.filter(function(s){return!s.async&&s.src&&!s.defer}).map(function(s){return util.getAbsoluteURL(s.src)})},getHostname:function(url){var a=window.document.createElement('a');a.href=url;return a.hostname}}
var score=0;var offending=[];var offendingDomains=[];var docDomain=document.domain;var styles=util.getCSSFiles(document.head);var scripts=util.getSynchJSFiles(document.head);styles.forEach(function(style){var styleDomain=util.getHostname(style);if(styleDomain!==docDomain){offending.push(style);if(offendingDomains.indexOf(styleDomain)===-1){offendingDomains.push(styleDomain);score+=10}}});scripts.forEach(function(script){var scriptDomain=util.getHostname(script);if(scriptDomain!==docDomain){offending.push(script);if(offendingDomains.indexOf(scriptDomain)===-1){offendingDomains.push(scriptDomain);score+=10}}});return[score,offending]}
function performanceThirdPartyAsyncJs(){var util={getAbsoluteURL:function(url){var a=window.document.createElement('a');a.href=url;return a.href},getHostname:function(url){var a=window.document.createElement('a');a.href=url;return a.hostname},getSynchJSFiles:function(parentElement){var scripts=Array.prototype.slice.call(parentElement.getElementsByTagName('script'));return scripts.filter(function(s){return!s.async&&s.src&&!s.defer}).map(function(s){return util.getAbsoluteURL(s.src)})}}
var patterns=['ajax.googleapis.com','apis.google.com','.google-analytics.com','connect.facebook.net','platform.twitter.com','code.jquery.com','platform.linkedin.com','.disqus.com','assets.pinterest.com','widgets.digg.com','.addthis.com','code.jquery.com','ad.doubleclick.net','.lognormal.com','embed.spotify.com'];function is3rdParty(url){var hostname=util.getHostname(url);var re;for(var i=0,len=patterns.length;i<len;i++){re=new RegExp(patterns[i]);if(re.test(hostname)){return!0}}
return!1}
var score=0;var offending=[];var scripts=util.getSynchJSFiles(document);for(var i=0,len=scripts.length;i<len;i++){if(is3rdParty(scripts[i])){offending.push(scripts[i]);score+=10}}
return[score,offending]}
return{'performanceScalingImages':performanceScalingImages(),'performanceCssPrint':performanceCssPrint(),'performanceFastRender':performanceFastRender(),'performanceGoogleTagManager':performanceGoogleTagManager(),'performanceInlineCss':performanceInlineCss(),'performanceJQuery':performanceJQuery(),'performanceSPOF':performanceSPOF(),'performanceThirdPartyAsyncJs':performanceThirdPartyAsyncJs()}})()